services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://switchyard.proxy.rlwy.net:53618/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=SFNIvOuZOPDNzyoFBODmgsFibmkuaMyg
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  db_data:
