services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=mysql.railway.internal://db:3306/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=XZbADUNQAYrNjMJrAgAwgLrtrEAWDIkZ
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: XZbADUNQAYrNjMJrAgAwgLrtrEAWDIkZ
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
